name: yuva
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # Core Firebase (essential)
  firebase_core: ^2.24.0
  firebase_auth: ^4.14.0
  
  # State Management
  get: ^4.6.6
  
  # UI Components
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  
  # Utilities
  path: ^1.8.3
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  
  # Location Services
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  permission_handler: ^11.0.1
  
  # Firebase Firestore
  cloud_firestore: ^4.13.0
  
  # Image Picker
  image_picker: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true



 