name: yuva
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.0
  firebase_auth: ^4.14.0
  cloud_firestore: ^4.13.0
  firebase_storage: ^11.5.0
  sms_autofill: ^2.3.0
  cupertino_icons: ^1.0.8
  
  # State Management
  get: ^4.6.6
  
  # Image and File Handling
  image_picker: ^1.0.4
  image: ^4.1.3
  
  # Location Services
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  
  # Date and Time
  intl: ^0.18.1
  
  # UI Components
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  
  # Utilities
  path: ^1.8.3
  permission_handler: ^11.0.1
  connectivity_plus: ^5.0.2
  shared_preferences: ^2.2.2
  
  # Analytics and Monitoring
  firebase_analytics: ^10.7.4
  firebase_crashlytics: ^3.4.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0



flutter:

  
  uses-material-design: true

 