import 'package:cloud_firestore/cloud_firestore.dart';
import '../models/course_model.dart';

class CourseService {
  final FirebaseFirestore _firestore = FirebaseFirestore.instance;

  // Search courses by name (case-insensitive)
  Future<List<CourseModel>> searchCourses(String query) async {
    try {
      if (query.trim().isEmpty) {
        return [];
      }
      final searchQuery = query.toLowerCase().trim();
      List<CourseModel> results = [];

      // First, try to get from Firestore
      try {
        final QuerySnapshot approvedCourses =
            await _firestore
                .collection('courses')
                .where('isApproved', isEqualTo: true)
                .get();

        for (var doc in approvedCourses.docs) {
          final course = CourseModel.fromMap(
            doc.id,
            doc.data() as Map<String, dynamic>,
          );
          if (course.name.toLowerCase().startsWith(searchQuery)) {
            results.add(course);
          }
        }
      } catch (e) {
        // If Firestore fails, use sample data
        print('Firestore search failed, using sample data: $e');
      }

      // If no results from Firestore, use sample data
      if (results.isEmpty) {
        final sampleCourses = [
          // Engineering Courses
          'Computer Science Engineering',
          'Mechanical Engineering',
          'Electrical Engineering',
          'Civil Engineering',
          'Chemical Engineering',
          'Electronics Engineering',
          'Information Technology',
          'Biotechnology Engineering',
          'Aerospace Engineering',
          'Automobile Engineering',
          'Production Engineering',
          'Industrial Engineering',
          'Textile Engineering',
          'Agricultural Engineering',
          'Mining Engineering',
          'Metallurgical Engineering',
          'Petroleum Engineering',
          'Nuclear Engineering',
          'Robotics Engineering', 'Artificial Intelligence', 'Data Science',
          'Machine Learning', 'Cyber Security', 'Software Engineering',
          'Computer Engineering',
          'Electronics and Communication',
          'Instrumentation Engineering',
          'Power Engineering',
          'Telecommunication Engineering',
          'Control Engineering',
          'VLSI Design',
          'Embedded Systems',
          'Network Engineering',
          'Cloud Computing',
          'Mobile Computing',
          'Web Technology',
          'Database Management',
          'Computer Networks',
          'Operating Systems', 'Computer Architecture', 'Digital Electronics',
          'Microprocessors',
          'Digital Signal Processing',
          'Communication Systems',
          'Satellite Communication',
          'Optical Communication',
          'Wireless Communication',
          'Digital Communication',
          'Analog Communication',
          'Microwave Engineering',
          'Antenna Theory',
          'Radar Systems',
          'Satellite Technology',
          'Fiber Optics',
          'Laser Technology',
          'Photonics',
          'Optoelectronics',
          'Quantum Electronics',
          'Semiconductor Physics', 'Solid State Physics', 'Plasma Physics',
          'Nuclear Physics', 'Particle Physics', 'Astrophysics', 'Cosmology',
          'Relativity',
          'Quantum Mechanics',
          'Thermodynamics',
          'Fluid Mechanics',
          'Heat Transfer',
          'Mass Transfer',
          'Momentum Transfer',
          'Reaction Engineering',
          'Process Control',
          'Plant Design',
          'Unit Operations',
          'Transport Phenomena',
          'Catalysis', 'Polymer Science', 'Nanotechnology', 'Materials Science',
          'Ceramic Engineering', 'Polymer Engineering', 'Composite Materials',
          'Smart Materials', 'Biomaterials', 'Metallurgy', 'Foundry Technology',
          'Welding Technology', 'Forging Technology', 'Casting Technology',
          'Heat Treatment', 'Surface Engineering', 'Corrosion Engineering',
          'Tribology',
          'Machine Design',
          'Dynamics of Machines',
          'Theory of Machines',
          'Mechanics of Materials',
          'Strength of Materials',
          'Structural Analysis',
          'Structural Design', 'Reinforced Concrete', 'Steel Structures',
          'Prestressed Concrete', 'Bridge Engineering', 'Highway Engineering',
          'Transportation Engineering', 'Traffic Engineering', 'Urban Planning',
          'Town Planning', 'Regional Planning', 'Environmental Planning',
          'Water Resources Engineering', 'Irrigation Engineering', 'Hydraulics',
          'Hydrology', 'Ocean Engineering', 'Coastal Engineering',
          'Port and Harbor Engineering',
          'Offshore Engineering',
          'Marine Engineering',
          'Naval Architecture', 'Ship Building', 'Submarine Technology',
          'Underwater Technology', 'Oceanography', 'Marine Biology',
          'Fisheries Science', 'Aquaculture', 'Marine Technology',
          'Ocean Technology', 'Marine Biotechnology', 'Marine Chemistry',
          'Marine Geology', 'Marine Physics', 'Marine Ecology',
          'Marine Conservation', 'Marine Pollution', 'Marine Resources',
          'Marine Policy', 'Marine Law', 'Marine Economics', 'Marine Tourism',
          'Marine Archaeology', 'Marine History', 'Marine Geography',
          'Marine Meteorology', 'Marine Climatology', 'Marine Seismology',
          'Marine Volcanology', 'Marine Tectonics', 'Marine Sedimentology',
          'Marine Stratigraphy', 'Marine Paleontology', 'Marine Evolution',
          'Marine Biodiversity', 'Marine Genetics', 'Marine Physiology',
          'Marine Biochemistry', 'Marine Microbiology', 'Marine Virology',
          'Marine Immunology', 'Marine Pathology', 'Marine Pharmacology',
          'Marine Toxicology', 'Marine Nutrition', 'Marine Medicine',
          'Marine Surgery', 'Marine Dentistry', 'Marine Nursing',
          'Marine Pharmacy',
          'Marine Physiotherapy',
          'Marine Occupational Therapy',
          'Marine Speech Therapy', 'Marine Psychology', 'Marine Psychiatry',
          'Marine Social Work', 'Marine Education', 'Marine Training',
          'Marine Research', 'Marine Development', 'Marine Innovation',
          'Marine Entrepreneurship',
          'Marine Management',
          'Marine Administration',
          'Marine Leadership', 'Marine Communication', 'Marine Journalism',
          'Marine Media',
          'Marine Arts',
          'Marine Literature',
          'Marine Philosophy',
          'Marine Religion', 'Marine Culture', 'Marine Heritage',
          'Marine Traditions', 'Marine Customs', 'Marine Festivals',
          'Marine Cuisine', 'Marine Fashion', 'Marine Architecture',
          'Marine Design', 'Marine Photography', 'Marine Cinematography',
          'Marine Music', 'Marine Dance', 'Marine Theater', 'Marine Sculpture',
          'Marine Painting', 'Marine Drawing', 'Marine Calligraphy',
          'Marine Pottery', 'Marine Weaving', 'Marine Embroidery',
          'Marine Jewelry', 'Marine Textiles', 'Marine Leather',
          'Marine Woodwork', 'Marine Metalwork', 'Marine Glasswork',
          'Marine Ceramics', 'Marine Plastics', 'Marine Composites',
          'Marine Nanomaterials',
          'Marine Biomaterials',
          'Marine Smart Materials',
          'Marine Functional Materials', 'Marine Structural Materials',
          'Marine Electronic Materials', 'Marine Magnetic Materials',
          'Marine Optical Materials', 'Marine Thermal Materials',
          'Marine Mechanical Materials', 'Marine Chemical Materials',
          'Marine Biological Materials', 'Marine Medical Materials',
          'Marine Dental Materials', 'Marine Pharmaceutical Materials',
          'Marine Cosmetic Materials', 'Marine Food Materials',
          'Marine Agricultural Materials', 'Marine Environmental Materials',
          'Marine Energy Materials', 'Marine Transportation Materials',
          'Marine Construction Materials', 'Marine Communication Materials',
          'Marine Information Materials', 'Marine Security Materials',
          'Marine Defense Materials', 'Marine Space Materials',
          'Marine Aviation Materials', 'Marine Automotive Materials',
          'Marine Railway Materials', 'Marine Shipbuilding Materials',
          'Marine Submarine Materials', 'Marine Aircraft Materials',
          'Marine Missile Materials', 'Marine Rocket Materials',
          'Marine Satellite Materials', 'Marine Telescope Materials',
          'Marine Microscope Materials', 'Marine Sensor Materials',
          'Marine Actuator Materials', 'Marine Controller Materials',
          'Marine Processor Materials', 'Marine Memory Materials',
          'Marine Storage Materials', 'Marine Display Materials',
          'Marine Input Materials', 'Marine Output Materials',
          'Marine Interface Materials', 'Marine Connector Materials',
          'Marine Cable Materials', 'Marine Wire Materials',
          'Marine Circuit Materials', 'Marine Board Materials',
          'Marine Chip Materials', 'Marine Package Materials',
          'Marine Housing Materials', 'Marine Case Materials',
          'Marine Cover Materials', 'Marine Seal Materials',
          'Marine Gasket Materials', 'Marine O-ring Materials',
          'Marine Bearing Materials', 'Marine Gear Materials',
          'Marine Belt Materials', 'Marine Chain Materials',
          'Marine Spring Materials', 'Marine Damper Materials',
          'Marine Brake Materials', 'Marine Clutch Materials',
          'Marine Coupling Materials', 'Marine Shaft Materials',
          'Marine Axle Materials', 'Marine Wheel Materials',
          'Marine Tire Materials', 'Marine Suspension Materials',
          'Marine Steering Materials', 'Marine Engine Materials',
          'Marine Transmission Materials', 'Marine Fuel Materials',
          'Marine Lubricant Materials', 'Marine Coolant Materials',
          'Marine Battery Materials', 'Marine Capacitor Materials',
          'Marine Resistor Materials', 'Marine Inductor Materials',
          'Marine Transformer Materials', 'Marine Motor Materials',
          'Marine Generator Materials', 'Marine Alternator Materials',
          'Marine Inverter Materials', 'Marine Converter Materials',
          'Marine Rectifier Materials', 'Marine Diode Materials',
          'Marine Transistor Materials', 'Marine Thyristor Materials',
          'Marine Triac Materials', 'Marine Diac Materials',
          'Marine UJT Materials', 'Marine PUT Materials',
          'Marine SCS Materials', 'Marine IGBT Materials',
          'Marine MOSFET Materials', 'Marine JFET Materials',
          'Marine BJT Materials', 'Marine FET Materials',
          'Marine IC Materials', 'Marine LSI Materials',
          'Marine VLSI Materials', 'Marine ULSI Materials',
          'Marine GSI Materials', 'Marine TSI Materials',
          'Marine PSI Materials', 'Marine ESI Materials',
          'Marine FSI Materials', 'Marine GSI Materials',
          'Marine HSI Materials', 'Marine ISI Materials',
          'Marine JSI Materials', 'Marine KSI Materials',
          'Marine LSI Materials', 'Marine MSI Materials',
          'Marine NSI Materials', 'Marine OSI Materials',
          'Marine PSI Materials', 'Marine QSI Materials',
          'Marine RSI Materials', 'Marine SSI Materials',
          'Marine TSI Materials', 'Marine USI Materials',
          'Marine VSI Materials', 'Marine WSI Materials',
          'Marine XSI Materials', 'Marine YSI Materials',
          'Marine ZSI Materials',
        ];

        for (String courseName in sampleCourses) {
          if (courseName.toLowerCase().startsWith(searchQuery)) {
            results.add(
              CourseModel(
                id: 'sample_${courseName.replaceAll(' ', '_').toLowerCase()}',
                name: courseName,
                isApproved: true,
                createdAt: DateTime.now(),
                updatedAt: DateTime.now(),
              ),
            );
          }
        }
      }

      results.sort((a, b) {
        final aName = a.name.toLowerCase();
        final bName = b.name.toLowerCase();
        if (aName == searchQuery && bName != searchQuery) return -1;
        if (bName == searchQuery && aName != searchQuery) return 1;
        return aName.compareTo(bName);
      });
      return results.take(10).toList();
    } catch (e) {
      throw Exception('Failed to search courses: $e');
    }
  }

  // Add course to pending courses collection
  Future<String> addPendingCourse(String courseName) async {
    try {
      final pendingCourse = CourseModel(
        id: '',
        name: courseName.trim(),
        isApproved: false,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      );
      final DocumentReference docRef = await _firestore
          .collection('pending_courses')
          .add(pendingCourse.toMap());
      return docRef.id;
    } catch (e) {
      throw Exception('Failed to add pending course: $e');
    }
  }

  // Check if course exists (approved or pending)
  Future<bool> courseExists(String courseName) async {
    try {
      final searchQuery = courseName.toLowerCase().trim();
      final QuerySnapshot approvedCourses =
          await _firestore
              .collection('courses')
              .where('isApproved', isEqualTo: true)
              .get();
      for (var doc in approvedCourses.docs) {
        final course = CourseModel.fromMap(
          doc.id,
          doc.data() as Map<String, dynamic>,
        );
        if (course.name.toLowerCase() == searchQuery) {
          return true;
        }
      }
      final QuerySnapshot pendingCourses =
          await _firestore.collection('pending_courses').get();
      for (var doc in pendingCourses.docs) {
        final course = CourseModel.fromMap(
          doc.id,
          doc.data() as Map<String, dynamic>,
        );
        if (course.name.toLowerCase() == searchQuery) {
          return true;
        }
      }
      return false;
    } catch (e) {
      throw Exception('Failed to check course existence: $e');
    }
  }

  // Initialize with some sample courses (for development/testing)
  Future<void> initializeSampleCourses() async {
    try {
      final sampleCourses = [
        // Engineering Courses
        'Computer Science Engineering',
        'Mechanical Engineering',
        'Electrical Engineering',
        'Civil Engineering',
        'Chemical Engineering',
        'Electronics Engineering',
        'Information Technology',
        'Biotechnology Engineering',
        'Aerospace Engineering',
        'Automobile Engineering',
        'Production Engineering',
        'Industrial Engineering',
        'Textile Engineering',
        'Agricultural Engineering',
        'Mining Engineering',
        'Metallurgical Engineering',
        'Petroleum Engineering',
        'Nuclear Engineering',
        'Robotics Engineering',
        'Artificial Intelligence',
        'Data Science',
        'Machine Learning',
        'Cyber Security',
        'Software Engineering',
        'Computer Engineering',
        'Electronics and Communication',
        'Instrumentation Engineering',
        'Power Engineering',
        'Telecommunication Engineering',
        'Control Engineering',
        'VLSI Design',
        'Embedded Systems',
        'Network Engineering',
        'Cloud Computing',
        'Mobile Computing',
        'Web Technology',
        'Database Management',
        'Computer Networks',
        'Operating Systems',
        'Computer Architecture',
        'Digital Electronics',
        'Microprocessors',
        'Digital Signal Processing',
        'Communication Systems',
        'Satellite Communication',
        'Optical Communication',
        'Wireless Communication',
        'Digital Communication',
        'Analog Communication',
        'Microwave Engineering',
        'Antenna Theory',
        'Radar Systems',
        'Satellite Technology',
        'Fiber Optics',
        'Laser Technology',
        'Photonics',
        'Optoelectronics',
        'Quantum Electronics',
        'Semiconductor Physics',
        'Solid State Physics',
        'Plasma Physics',
        'Nuclear Physics',
        'Particle Physics',
        'Astrophysics',
        'Cosmology',
        'Relativity',
        'Quantum Mechanics',
        'Thermodynamics',
        'Fluid Mechanics',
        'Heat Transfer',
        'Mass Transfer',
        'Momentum Transfer',
        'Reaction Engineering',
        'Process Control',
        'Plant Design',
        'Unit Operations',
        'Transport Phenomena',
        'Catalysis',
        'Polymer Science',
        'Nanotechnology',
        'Materials Science',
        'Ceramic Engineering',
        'Polymer Engineering',
        'Composite Materials',
        'Smart Materials',
        'Biomaterials',
        'Metallurgy',
        'Foundry Technology',
        'Welding Technology',
        'Forging Technology',
        'Casting Technology',
        'Heat Treatment',
        'Surface Engineering',
        'Corrosion Engineering',
        'Tribology',
        'Machine Design',
        'Dynamics of Machines',
        'Theory of Machines',
        'Mechanics of Materials',
        'Strength of Materials',
        'Structural Analysis',
        'Structural Design',
        'Reinforced Concrete',
        'Steel Structures',
        'Prestressed Concrete',
        'Bridge Engineering',
        'Highway Engineering',
        'Transportation Engineering',
        'Traffic Engineering',
        'Urban Planning',
        'Town Planning',
        'Regional Planning',
        'Environmental Planning',
        'Water Resources Engineering',
        'Irrigation Engineering',
        'Hydraulics',
        'Hydrology',
        'Ocean Engineering',
        'Coastal Engineering',
        'Port and Harbor Engineering',
        'Offshore Engineering',
        'Marine Engineering',
        'Naval Architecture',
        'Ship Building',
        'Submarine Technology',
        'Underwater Technology',
        'Oceanography',
        'Marine Biology',
        'Fisheries Science',
        'Aquaculture',
        'Marine Technology',
        'Ocean Technology',
        'Marine Biotechnology',
        'Marine Chemistry',
        'Marine Geology',
        'Marine Physics',
        'Marine Ecology',
        'Marine Conservation',
        'Marine Pollution',
        'Marine Resources',
        'Marine Policy',
        'Marine Law',
        'Marine Economics',
        'Marine Tourism',
        'Marine Archaeology',
        'Marine History',
        'Marine Geography',
        'Marine Meteorology',
        'Marine Climatology',
        'Marine Seismology',
        'Marine Volcanology',
        'Marine Tectonics',
        'Marine Sedimentology',
        'Marine Stratigraphy',
        'Marine Paleontology',
        'Marine Evolution',
        'Marine Biodiversity',
        'Marine Genetics',
        'Marine Physiology',
        'Marine Biochemistry',
        'Marine Microbiology',
        'Marine Virology',
        'Marine Immunology',
        'Marine Pathology',
        'Marine Pharmacology',
        'Marine Toxicology',
        'Marine Nutrition',
        'Marine Medicine',
        'Marine Surgery',
        'Marine Dentistry',
        'Marine Nursing',
        'Marine Pharmacy',
        'Marine Physiotherapy',
        'Marine Occupational Therapy',
        'Marine Speech Therapy',
        'Marine Psychology',
        'Marine Psychiatry',
        'Marine Social Work',
        'Marine Education',
        'Marine Training',
        'Marine Research',
        'Marine Development',
        'Marine Innovation',
        'Marine Entrepreneurship',
        'Marine Management',
        'Marine Administration',
        'Marine Leadership',
        'Marine Communication',
        'Marine Journalism',
        'Marine Media',
        'Marine Arts',
        'Marine Literature',
        'Marine Philosophy',
        'Marine Religion',
        'Marine Culture',
        'Marine Heritage',
        'Marine Traditions',
        'Marine Customs',
        'Marine Festivals',
        'Marine Cuisine',
        'Marine Fashion',
        'Marine Architecture',
        'Marine Design',
        'Marine Photography',
        'Marine Cinematography',
        'Marine Music',
        'Marine Dance',
        'Marine Theater',
        'Marine Sculpture',
        'Marine Painting',
        'Marine Drawing',
        'Marine Calligraphy',
        'Marine Pottery',
        'Marine Weaving',
        'Marine Embroidery',
        'Marine Jewelry',
        'Marine Textiles',
        'Marine Leather',
        'Marine Woodwork',
        'Marine Metalwork',
        'Marine Glasswork',
        'Marine Ceramics',
        'Marine Plastics',
        'Marine Composites',
        'Marine Nanomaterials',
        'Marine Biomaterials',
        'Marine Smart Materials',
        'Marine Functional Materials',
        'Marine Structural Materials',
        'Marine Electronic Materials',
        'Marine Magnetic Materials',
        'Marine Optical Materials',
        'Marine Thermal Materials',
        'Marine Mechanical Materials',
        'Marine Chemical Materials',
        'Marine Biological Materials',
        'Marine Medical Materials',
        'Marine Dental Materials',
        'Marine Pharmaceutical Materials',
        'Marine Cosmetic Materials',
        'Marine Food Materials',
        'Marine Agricultural Materials',
        'Marine Environmental Materials',
        'Marine Energy Materials',
        'Marine Transportation Materials',
        'Marine Construction Materials',
        'Marine Communication Materials',
        'Marine Information Materials',
        'Marine Security Materials',
        'Marine Defense Materials',
        'Marine Space Materials',
        'Marine Aviation Materials',
        'Marine Automotive Materials',
        'Marine Railway Materials',
        'Marine Shipbuilding Materials',
        'Marine Submarine Materials',
        'Marine Aircraft Materials',
        'Marine Missile Materials',
        'Marine Rocket Materials',
        'Marine Satellite Materials',
        'Marine Telescope Materials',
        'Marine Microscope Materials',
        'Marine Sensor Materials',
        'Marine Actuator Materials',
        'Marine Controller Materials',
        'Marine Processor Materials',
        'Marine Memory Materials',
        'Marine Storage Materials',
        'Marine Display Materials',
        'Marine Input Materials',
        'Marine Output Materials',
        'Marine Interface Materials',
        'Marine Connector Materials',
        'Marine Cable Materials',
        'Marine Wire Materials',
        'Marine Circuit Materials',
        'Marine Board Materials',
        'Marine Chip Materials',
        'Marine Package Materials',
        'Marine Housing Materials',
        'Marine Case Materials',
        'Marine Cover Materials',
        'Marine Seal Materials',
        'Marine Gasket Materials',
        'Marine O-ring Materials',
        'Marine Bearing Materials',
        'Marine Gear Materials',
        'Marine Belt Materials',
        'Marine Chain Materials',
        'Marine Spring Materials',
        'Marine Damper Materials',
        'Marine Brake Materials',
        'Marine Clutch Materials',
        'Marine Coupling Materials',
        'Marine Shaft Materials',
        'Marine Axle Materials',
        'Marine Wheel Materials',
        'Marine Tire Materials',
        'Marine Suspension Materials',
        'Marine Steering Materials',
        'Marine Engine Materials',
        'Marine Transmission Materials',
        'Marine Fuel Materials',
        'Marine Lubricant Materials',
        'Marine Coolant Materials',
        'Marine Battery Materials',
        'Marine Capacitor Materials',
        'Marine Resistor Materials',
        'Marine Inductor Materials',
        'Marine Transformer Materials',
        'Marine Motor Materials',
        'Marine Generator Materials',
        'Marine Alternator Materials',
        'Marine Inverter Materials',
        'Marine Converter Materials',
        'Marine Rectifier Materials',
        'Marine Diode Materials',
        'Marine Transistor Materials',
        'Marine Thyristor Materials',
        'Marine Triac Materials',
        'Marine Diac Materials',
        'Marine UJT Materials',
        'Marine PUT Materials',
        'Marine SCS Materials',
        'Marine IGBT Materials',
        'Marine MOSFET Materials',
        'Marine JFET Materials',
        'Marine BJT Materials',
        'Marine FET Materials',
        'Marine IC Materials',
        'Marine LSI Materials',
        'Marine VLSI Materials',
        'Marine ULSI Materials',
        'Marine GSI Materials',
        'Marine TSI Materials',
        'Marine PSI Materials',
        'Marine ESI Materials',
        'Marine FSI Materials',
        'Marine GSI Materials',
        'Marine HSI Materials',
        'Marine ISI Materials',
        'Marine JSI Materials',
        'Marine KSI Materials',
        'Marine LSI Materials',
        'Marine MSI Materials',
        'Marine NSI Materials',
        'Marine OSI Materials',
        'Marine PSI Materials',
        'Marine QSI Materials',
        'Marine RSI Materials',
        'Marine SSI Materials',
        'Marine TSI Materials',
        'Marine USI Materials',
        'Marine VSI Materials',
        'Marine WSI Materials',
        'Marine XSI Materials',
        'Marine YSI Materials',
        'Marine ZSI Materials',
      ];
      final QuerySnapshot existingCourses =
          await _firestore
              .collection('courses')
              .where('isApproved', isEqualTo: true)
              .get();
      if (existingCourses.docs.isNotEmpty) {
        return;
      }
      for (String courseName in sampleCourses) {
        final course = CourseModel(
          id: '',
          name: courseName,
          isApproved: true,
          createdAt: DateTime.now(),
          updatedAt: DateTime.now(),
        );
        await _firestore.collection('courses').add(course.toMap());
      }
    } catch (e) {
      throw Exception('Failed to initialize sample courses: $e');
    }
  }
}
