import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart'; // Add Firebase Core
import 'firebase_options.dart'; // Generated by FlutterFire CLI
import 'screens/welcome_screen.dart'; // Updated path
import 'screens/create_account_screen.dart'; // Updated path
import 'screens/login_screen.dart'; // Updated path
import 'screens/otp_verification_screen.dart'; // Import the updated OTP screen

void main() async {
  WidgetsFlutterBinding.ensureInitialized(); // Ensure Flutter bindings are initialized
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform, // Load Firebase config
  );
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Yuva',
      theme: ThemeData(
        primarySwatch: Colors.purple,
      ),
      initialRoute: '/welcome',
      routes: {
        '/welcome': (context) => const WelcomeScreen(),
        '/create-account': (context) => const CreateAccountScreen(),
        '/login': (context) => const LoginScreen(),
        '/otp-verification': (context) => const OTPVerificationScreen(), // Points to the updated screen
        '/profile': (context) => const ProfileScreen(),
      },
    );
  }
}

// Placeholder for ProfileScreen
class ProfileScreen extends StatelessWidget {
  const ProfileScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Profile')),
      body: const Center(
        child: Text('Welcome to your Profile!'),
      ),
    );
  }
}